### ISSUE TITLE
Bugged overlay after leaving vc

### ISSUE THREAD

**Issue by e6voe9** [Hacksore/overlayed-electron#10]
After leaving vc it stays for some reasons.

![image](https://github.com/Hacksore/overlayed/assets/54411613/983f2de8-fd1f-47da-8aa4-581bb8950329)

It never happened with List styling option. It might be related to Grid, but I have no idea.

MacOS 13.1

**Comment by Hacksore** [comment]
Yep it's broked sometimes

![image](https://github.com/Hacksore/overlayed/assets/996134/3b27aca3-6a30-4810-9402-b9fc97cb1a53)
