### ISSUE TITLE
Request access to overlayed - Comment your discord user/discriminator

### ISSUE THREAD

**Issue by alex-oser** [Hacksore/overlayed-electron#2]
2017 MacBook Pro running Big Sur 11.5.1

After going through the Discord authorization, the app does not load me in I just stay on the Authorize screen. There also are not any logs coming through on the debugging panel :(

**Comment by Hacksore** [comment]
Ruh-roh - I think I see the issue now.

Discord doesn't seem to want to grant anyone other than me, the owner of the OAuth app, to generate tokens that have access to interact with RPC.

Tried using the [login URL](https://discord.com/api/oauth2/authorize?client_id=905987126099836938&redirect_uri=https%3A%2F%2Fauth.overlayed.dev%2Foauth%2Fcallback&response_type=code&scope=rpc) on a different account and got an OAuth error.
![image](https://user-images.githubusercontent.com/996134/143688694-2c7554e1-a985-47ac-978a-6f1e450b17f8.png)


Probably falls into line with the banner on the [discord docs page](https://discord.com/developers/docs/topics/rpc), so I guess we have HODL until discord opens the gate 😢 .

![image](https://user-images.githubusercontent.com/996134/143688614-61ee33c8-d1df-4172-a1a9-ae3e92e9e809.png)

**Comment by Hacksore** [comment]
I can allow at least 50 people in for now via the testers section which I have confirmed to work.

Let's use this issue for people to request access, just leave a comment with your discord username and discriminator. ex: `Hacksore#1984`

@alex-oser dropped an invite to you 😅 

Note you need to add me `Hacksore#1984` as a friend before I can add you.

**Comment by cdharris** [comment]
charris#6428 please @Hacksore :man_scientist: :atom_symbol: :bow:

**Comment by Hacksore** [comment]
@cdharris I can invite you but keep in mind auth is likely going to be completely broken until I can finish the rework in #3.

Feel free to join the discord and I can share any progress there.

**Comment by MrJDucky** [comment]
MrJDucky Esq. III#6969

**Comment by true-Grand** [comment]
Leo Edwards#6388 Would love to try this out!

**Comment by Rukyta** [comment]
RMC#5866 .hi. just sent you friend request. after years of overlay problems its great that youve sorted it out.thank you

**Comment by campbellcharlie** [comment]
Darkness#8361 would love to try this out

**Comment by CoolDog22YT** [comment]
Affinityraee(they/them)#6860 I really want to try this

**Comment by CoolDog22YT** [comment]
When I got the dm it auto marked it as spam and wouldn't let me accept the dm pls send it again

**Comment by Hacksore** [comment]
@CoolDog22YT it's not a DM, check you or email you use for your account.

You're gonna get an email from discord that is an invite to my app.

**Comment by CoolDog22YT** [comment]
Okay thank you

**Comment by DevAmiyo** [comment]
Amiyo#7978  I wanna try this...

**Comment by Hacksore** [comment]
> Amiyo#7978  I wanna try this...

@DevAmiyo accept my friend request and I can add you.

**Comment by HEROshineMC** [comment]
I would love to be apart of this too! :) My Discord is HERO#2795

**Comment by SiemenM** [comment]
@Hacksore  Can i gain asses to the tool? i would love!!! My discord is Siemen M.#4853

**Comment by Veneficus2130** [comment]
Hello! Can I get access to the tool please?! <3 Been waiting for a good overlay for Macs foreverrrr!
My discord is **Veneficus#2723** Thanks!

**Comment by Berna1337** [comment]
Hey, can I have access to it? **Berna#4495**

**Comment by Obsouleet** [comment]
Hey - thanks for coding this fine piece of software!

Would you please add me to the list:  Finnagain#0507

Thanks in advance

**Comment by jstairs** [comment]
Please add me as well:
Zaine#9080

**Comment by Hacksore** [comment]
@jstairs FYI you have to be my friend before I can invite you 😅

![image](https://user-images.githubusercontent.com/996134/205947403-1fcc4ec7-2b0c-4513-9ba6-c694ed3727dd.png)

**Comment by Mostfamous** [comment]
Unsensibel#6197, please add me :) thx a lot

**Comment by derN3rd** [comment]
Would like to try this as well, thanks
derN3rd#0001

**Comment by Mostfamous** [comment]
> Would like to try this as well, thanks
> derN3rd#0001

Its runs very well.

**Comment by Saad-Mehr** [comment]
wyndfyre#7055, i would also like to try this out

**Comment by Jobeso** [comment]
Awesome work! Would appreciate an invite as well.
Jobeso#8649

**Comment by EvaxTheFox** [comment]
[Evax#8388](https://discord.com/users/1034381088316981309)

**Comment by chrisbialek** [comment]
SWOOP#4341 OR SWOOP#0001

**Comment by LuluHRO** [comment]
Hachez#6918

**Comment by Hacksore** [comment]
I will stop accepting invites because I hit the limit on the app testers.

If discord ever allows devs to use the API properly I might come back to this project but for now consider it vaporware.

**Comment by massdingit** [comment]
hmmph, best if you copy the same thing to a different app, and then start there since you'd have space for 50 extra people

**Comment by Hacksore** [comment]
> hmmph, best if you copy the same thing to a different app, and then start there since you'd have space for 50 extra people

@masdin655 Def possible but at but not something I'd like to do as of now.

few options are to unblock new folks:
- Roll your own oauth app with discord and forking this project (hard)
- Use [streamkit](https://streamkit.discord.com/) and extracting the token and placing it into the `auth.json` (easy)

There might be other workarounds or solutions but this is the best advice I can offer at this time.
