### ISSUE TITLE
Login request asks for Discord credentials in a window it owns

### ISSUE THREAD

**Issue by Spice-King** [Hacksore/overlayed-electron#3]
This is *very* sketch looking and probably not what you intend to do. I'm familiar enough to know that you can manipulate a window pointed to another site within Electron. While I doubt you mean to, this kinda tripped every single red flag possible in my head since it would be a marginal amount of effort to scrape credentials or auth tokens.

It's the same reason I don't like how you can embed Stripe into your own page in a way that blurs what is what, making it really look like you are asking customers to punch in CC details into your random site rather than a trusted payment processor (or at least a more well known place that has more skin in the game to act right).

Might I really suggest changing that so you open up the user's preferred browser rather than opening up a window you control.

**Comment by Hacksore** [comment]
I fully support this as what I have now is very bad by just scraping the token out of the DOM of the electron browser window.

I'd love to use the default browser but how do we get the token back to electron after auth is complete?

**Comment by Spice-King** [comment]
The gist of it, spin up a local web server on some high port number, configure a redirect localhost URL with said port in the oAuth2 section of the Discord app, then use the URL generator to pick out both permissions and a redirect URL. After authenticated and authorized, Discord will redirect the main browser back, with the useful oAuth2 bit in URL params.

It's documented [here](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant) in far more detail.

**Comment by Hacksore** [comment]
A server with a very high port (ex `http://localhost:62135`) on the electron side is something I'm looking into now but I'd need to post that back over.

Keep in mind we don't do token generation on the client as that would expose my client's secret which would not be right. The OAuth dance right now is being done at `auth.overlayed.dev` and the code is here https://github.com/Hacksore/overlayed-api

If you can think of any other apps that do this so I can have a peek at their flow that'd be helpful. 

So ideal flow is in my eyes is:

1. Client clicks the login button
1. Open default browser with redirect URL
1. Backend fetches token with client id/secret
1. Discord redirects to `overlayed.dev/success`
1. Web app will `POST` token to `localhost:62135`
1. Electron now has the token

**Comment by Hacksore** [comment]
Seems another way is to register a custom protocol handler and I can share the payload that way.

Not sure which is better at this point but will experiment with both options.

**Comment by Hacksore** [comment]
So I stuck with the express service running locally as opposed to the protocol handler as it's a better UX overall.

With a protocol handler, you'd have to click three times to log in and with this implementation, it is only two.

Part of the authentication dance now happens on [overlayed.dev](https://github.com/Hacksore/overlayed-website) and token generation is still taking place on [auth.overlayed.dev](https://github.com/Hacksore/overlayed-api).

@Spice-King feel free to add any more feedback here but I'm going to mark this as resolved with f9f6209445b315378ceed0b2cda1e23a9e16abab

**Comment by Spice-King** [comment]
Sorry, meant to reply ages ago, just never got a chance with work and life keeping me busy then forgetting after I read it.

I forget that Google offers client side keys that don't have secrets and that is not really a standard Discord does. You have largely done what I've would have done.
