### ISSUE TITLE
Discord client connect

### ISSUE THREAD

**Issue by CoolDog22YT** [Hacksore/overlayed-electron#6]
When I click check for discord nothing happens and it doesn't work. I have discord open too.

**Comment by Hacksore** [comment]
Fairly certain this is fixed with https://github.com/Hacksore/overlayed/commit/9f38c80e1ff884247c898e29c02bda8f911c6368 but I have not released a new version yet.

**Comment by Hacksore** [comment]
The workaround, for now, is to make sure discord is running before opening overlayed.

**Comment by CoolDog22YT** [comment]
okay

**Comment by CoolDog22YT** [comment]
just reinstalled and cleared files after a couple times it works now
