### ISSUE TITLE
Failed to Connect - Discord Open?!

### ISSUE THREAD

**Issue by Veneficus2130** [Hacksore/overlayed-electron#9]
<img width="384" alt="Screenshot 2022-12-04 at 8 40 34 pm" src="https://user-images.githubusercontent.com/115164335/205514380-f7a8c4b7-53cb-429d-b906-410f92929fd2.png">

Keep getting this message when the append discord is open. Tried closing both and reopening.

**Comment by Hacksore** [comment]
Yeah there is some bug in the discord detection logic and I run into this pretty often. One thing I had success with is this.

- Close Discord and Overlayed
- Wait a few seconds
- Open Discord and let it launch fully
- Open Overlayed

This may or may not work but I have had little bandwidth to continue working on this project.

**Comment by Hacksore** [comment]
Actually it's probably that your auth token is expired, please delete the `auth.json` file and restart Overlayed.

Delete this file and restart Overlayed.
Windows: `%APPDATA%\Overlayed\auth.json`
macOS: `~/Library/Application\ Support/overlayed/auth.json`
linux: ???

**Comment by Veneficus2130** [comment]
This fixed it, thanks 👍
